#' extract a transition matrix from a BirdFlowR model
#'
#' get_transition will return a transition matrix between the timesteps
#' indicated in the transition code `x` from a BirdFlow object, possibly
#' calculating them from marginals.
#'
#' @param x transition code. E.g. "T_01-02"
#' @param bf a BirdFlow object
#'
#' @return a transition matrix
#'
#' @details `get_transition` will construct a transition matrix from the marginals
#' if `bf`doesn't have transitions, or return the relevant stored transition
#' matrix if it does.
#'
#' The nomenclature for a transition is "T_\[from\]-\[to\]" where \[from\] and
#' \[to\] are timesteps padded with zeros. Direction is important; "T_03-04"
#' represents a transition backward in time.
#'
#' The transition matrices are structured such that you multiply the
#' matrix by the distribution to project either forward or backwards.
#' If more than one distribution is projected at once they should be
#' stored in columns of a matrix with dimensions(n_active, n_distributions).
#'
#' Given a marginal in which the cell \[i, j\] represents the probability of the
#' bird being in state i in the prior timestep and state j in the next, to
#' generate the forward transition matrix we divide each row of the marginal by
#' its sum and then transpose. Backwards transitions matrices are generated by
#' dividing each column by its sum, without transposing.
#'
#' @seealso [lookup_transitions] will generate a list of the transitions needed
#' to forecast or route between two points in time that can then be passed to
#' this function. The internal function [transition_from_marginal] does the
#' calculations.
#' @export
get_transition <- function(x, bf){

   if(bf$metadata$has_transitions){
     return(bf$transition[[x]])
   }

  if(bf$metadata$has_marginals){
    ind <- bf$marginals$index
    i <- which(ind$transition == x)
    if(length(i) == 0){
      stop("There is no marginal for transition ", x)
    }
    m <- bf$marginals[[ind$marginal[i]]]
    direction <- ind$direction[i]
    return(transition_from_marginal(m, direction))
  }
  stop("The BirdFlow object should have either transitions or marginals")
}

#' transition_from_marginal
#'
#' internal function to generate a transition matrix from a marginal
#'
#' @details this is called from get_transition. If at some point we decide
#' to store transitions rather than marginals it will also be called from
#' import_birdflow.
#'
#' @param m a marginal
#' @param direction the desired transition direction, either "forward" or
#' "backward"
#'
#' @return a transition matrix formulated such that you multiply the matrix by
#' a distribution to project the distribution.  See [get_transition] for more
#' details.
transition_from_marginal <- function(m, direction){
  if(direction == "forward"){
    return( t( m /rowSums(m) ) )
  }
  if(direction == "backward"){
    return( apply(m, 2, function(x) x / sum(x)))
  }
  stop("Direction must be forward or backward")
}

